services:
  expo:
    build: .
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - .:/usr/src/Aulos
      - /usr/src/Aulos/node_modules
    command: npx expo start
